name: Podcast Generator

author: Not Me

description: Generates podcast feeds from a YAML file

inputs:
  email:
    description: Committer email address
    required: false
    default: github-actions@users.noreply.github.com

  name:
    description: Committer name
    required: false
    default: github-actions

runs:
  using: docker
  image: Dockerfile

branding:
  icon: git-branch
  color: red